### ISSUE TITLE
Incorrect Folder name

### ISSUE THREAD

**Issue by ciaranCern** [VHDLTool/VHDLHandbook#12]
Hi,

The folder VHDLTool/VHDL_Handbook_CNE/RuleSets is incorrect and I did not manage to build a document because of this. Changing the folder name to Rulesets without the uppercase s solved the issue.

Ciaran

**Comment by LeFl0w** [comment]
Thanks a lot.
this should be fixed now in the last commit in VHDLTool/VHDL_Handbook_CNE.
I also updated submodules in VHDL_Handbook_Toolchain to update src_handbook CNE and STD to this commit.
