### ISSUE TITLE
No outline in resulting pdf file

### ISSUE THREAD

**Issue by csantosb** [VHDLTool/VHDLHandbook#6]
Is there a way to get an outline (index) in the provided output file ? It might be helpful for navigating.

**Comment by LeFl0w** [comment]
I'm not sure to understand your requested as there is already a table of content in the resulting PDF.
Anyway you can change the formatting of the pdf file by modyfying steelsheets during the docbook step.

**Comment by csantosb** [comment]
I mean french "signets" or english "bookmarks" in the file, as shown [here](http://bit.ly/1QgDkGa)

**Comment by LeFl0w** [comment]
yes indeed it would be great.
I'll have to check in FOP if it is easily feasible

**Comment by mickael-carl** [comment]
The solution was found on the following website: https://brunovernay.wordpress.com/2006/06/20/docbook-publishing-as-pdf-with-bookmarks-on-windows/

Adding the parameters as mentionned there seems to work (tested under Windows with Sumatra PDF and Adobe Reader).
