### ISSUE TITLE
Crash with Saxon 9.7

### ISSUE THREAD

**Issue by mickael-carl** [VHDLTool/VHDLHandbook#7]
Using newer versions of the Saxon XSL processor gives the following error:
"HandbookVHDL\VHDLHandbook\stylesheets\docbook\fo\param.xsl:200:19: Fatal Error! Namespace prefix 'exsl' has not been declared"

This crash happened with Saxon version 9.7.0.1. It does not appear using Saxon 9.6.0.7 or downwards.

EDIT: The problem is docbook related. It is either coming from Saxon (in which case we'll just have to wait for a fix) or from docbook. And if it's coming from docbook then we might not be able to fix it easily since the handbook uses a custom version of docbook.

**Comment by ond1** [comment]
Hi, we have now hit this ourselves. It is a shame you did not tell us about it. A patch will be issued in the next maintenance release. See bug issue for details: https://saxonica.plan.io/issues/2809

**Comment by ond1** [comment]
Hi, we have now hit this ourselves. It is a shame you did not tell us about it. A patch will be issued in the next maintenance release. See bug issue for details: https://saxonica.plan.io/issues/2809
