### ISSUE TITLE
regression on bookmark

### ISSUE THREAD

**Issue by LeFl0w** [VHDLTool/VHDLHandbook#9]
Bookmark inside generated  pdf no longer shows on.

**Comment by mickael-carl** [comment]
It seems the fix added by ca6fce9 and 25d2f8b is not present anymore in the [build.docbook.xml](https://github.com/VHDLTool/VHDL_Handbook_Toolchain/blob/master/Scripts/build.docbook.xml) file.

**Comment by LeFl0w** [comment]
close with commit ff3c5a44777073afa9168b2b8da973c870eb0dde
